# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 47dbd4e6b966314c0a9558dff25fd486881e75b626a647aefcaaddccccf9254bc5c11f340a111e99eb28a36c2bfdc4526fe7acbc5114e35491a5fd8ed8c4c714

test:
  secret_key_base: 62e3f2965da6ff4bf3b5d76a6805b6f7b42caf2846aa99ff28e0b36db624fa781cf9c6e4fa22f4cb30ee60f7181ebde73829f4bcbbe3ae815b4b7a0199950075

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
